---
- name: Setup Kali Machine
  hosts: kali
  become: true
  vars:
    sysctl_conf_path: /etc/sysctl.conf
    ipv6_disabled: 1
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Basic packages
      apt:
        name:
          - htop
          - curl
          - jq
          - git
          - mercurial
          - make
          - binutils
          - bison
          - gcc
          - build-essential
          - docker.io
          - python3.11-venv
          - proxychains4
          - tor
        state: present

    - name: Enable Docker service
      become: true
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install nvm
      vars:
        nvm_version: 0.39.3
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash
        creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh

    - name: Install node and set version
      shell: >
        /bin/bash -c "source ~/.nvm/nvm.sh && nvm install --lts"
        creates=/home/{{ ansible_user_id }}/.nvm/alias

    - name: Clone Repository
      ignore_errors: true
      git:
        repo: "https://github.com/opsdisk/pagodo.git"
        dest: "/root/pagodo"

    - name: Disable IPv6 on all interfaces
      lineinfile:
        path: "{{ sysctl_conf_path }}"
        line: "{{ item }}"
        state: present
      with_items:
        - "net.ipv6.conf.all.disable_ipv6 = {{ ipv6_disabled }}"
        - "net.ipv6.conf.default.disable_ipv6 = {{ ipv6_disabled }}"
        - "net.ipv6.conf.lo.disable_ipv6 = {{ ipv6_disabled }}"
      notify: reload sysctl

    - name: Reboot
      reboot:
        reboot_timeout: 300
        msg: "rebooting..."

  handlers:
    - name: Reload sysctl settings
      command: sysctl -p
