- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Common packages
  apt:
    name:
      - htop
      - curl
      - jq
      - git
      - mercurial
      - make
      - binutils
      - bison
      - gcc
      - build-essential
      - python3.11-venv
      - zsh
    state: present
