---
- name: Disable IPv6 on all interfaces
  lineinfile:
    path: "{{ sysctl_conf_path }}"
    line: "{{ item }}"
    state: present
  with_items:
    - "net.ipv6.conf.all.disable_ipv6 = {{ ipv6_disabled }}"
    - "net.ipv6.conf.default.disable_ipv6 = {{ ipv6_disabled }}"
    - "net.ipv6.conf.lo.disable_ipv6 = {{ ipv6_disabled }}"
  notify: Reload sysctl settings
