---
- name: Download Docker Compose installation script
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Verify Docker Compose installation
  become: true
  command: docker-compose --version
  register: docker_compose_output

- name: Print Docker Compose version
  become: true
  debug:
    var: docker_compose_output.stdout
