---
- name: Setup basic kali box
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
  roles:
    - build-packages
    - proxy-utilities
    - disable-v6
    - nvm
    - gvm
    - docker
    - pagodo
    - nuclei
    - reboot
